### ISSUE TITLE
Date Time Issue

### ISSUE THREAD

**Issue by ceinem** [residentsummer/watoi#23]
Ok, this one is nothing serious, but an interesting curiosity. Instead of using an empty fresh iCloud backup, I accidentally used a 2 years old iCloud backup, which contained millions of messages. (from the time before I switched to an android phone). I noticed this, but wanted to see if it would still work. 
For all the chats that were both in the old iCloud backup and the new Android backup, the chats did merge, but the ordering of messages was wrong. The old iCloud messages were displayed under (so as newer) than the new messages from the android script. even though all messages are labeled with the correct date and time. 
So now I scroll back into the past, it starts with messages from 2017, then 2016, 2015, 2014, 2013 and then there is suddenly 2019 and 2018. 

It's no problem for me, because it's still searchable, but still weird. I guess it's a bug somewhere in the ordering of how messages get added to the database. 

Also I lost the messages of the past 2 days, but that's probably me messing up in extracting the unencrypted msgstore.db

**Comment by residentsummer** [comment]
Hi, @ceinem !

Yeah, I had this issue when working on the initial implementation of the tool. Whatsapp don't use date for sorting messages. Instead there is a dedicated `sort` field. Tool reestablishes ordering like this:

* old messages (from Android backup) are inserted with increasing `sort` field, [starting from 0](https://github.com/residentsummer/watoi/blob/master/watoi/main.m#L444)
* `sort` field for newer messages (those already in iOS backup - arrived after you've set up Whatsapp on iOS, but before migration process started) [is increased by the number](https://github.com/residentsummer/watoi/blob/master/watoi/main.m#L529) of messages in the old backup (in the corresponding chat/group)

This workaround assumed that in the iOS backup all messages are newer than in Android's. I didn't implement proper solution (sorting by date) because going over large backups to fix sorting was quite time consuming (maybe due to the perf bug I resolved later).

Feel free to reopen (or ask on gitter) if you need more info.
