### ISSUE TITLE
Feature: migrate from ios to Android

### ISSUE THREAD

**Issue by WOLFI3654** [residentsummer/watoi#25]
Is it possible to modify the program so you can migrate the ios database to an Android database?

**Comment by residentsummer** [comment]
That's possible in theory, but not sure if it's practical to do so. In fact, migration to Android can be as simple as a couple of SQL scripts - easy to run (on any OS) and fix. This utility (watoi) was born due to difficulties of creating CoreData files (Apple's database "format") with SQL scripts approach. And because of it's usage of Apple's frameworks it can only be run on MacOS. Anyway, I have no plans to implement this.

**Comment by Mc-muffin** [comment]
There's actually an Android app that does this, is called WazzapMigrator in the play store, it's paid however.

**Comment by KoNickss** [comment]
Whatsapp added this as an official feature, you can close this issue.
Lets hope they do the same for Android->IOS
