### ISSUE TITLE
Question: migrating without a mac

### ISSUE THREAD

**Issue by seba5496** [residentsummer/watoi#27]
Hey there, just a simple question, is there a way of avoiding the use of a mac? I don't have access to one, and I need to migrate my whatsapp chats to an iPhone.

Thanks in advance.

**Comment by residentsummer** [comment]
Hi, @seba5496 ! I've not attempted to build the utility on other platforms and the last time I've checked chances to succeed were low due to many missing pieces. You can try to rent a mac with remote access. Though, it does not remove the need of some kind of local PC to run iTunes for backup and restore process.

**Comment by 5E7EN** [comment]
I've had success in using a hackintosh instance via VMware (although discretion is advised as I'm not entirely sure of its legality)... 

Let me know if you'd like more info/step-by-step instructions.

**Comment by residentsummer** [comment]
@5E7EN I'd like to thank you for taking time and providing instructions for less experienced users. Added link to your guide to the README. 👏👏👏
