### ISSUE TITLE
Noob here

### ISSUE THREAD

**Issue by jorgallo** [residentsummer/watoi#5]
I want to transfer my WA chats from an S6 Edge to an iPhone, love your guide, I have my backup unencrypted and my Android Db but i really do not understand this step. I do however know where the backup is located, I just don't know what the path for the sqlite file is. Any help pls? :(

Locate Whatsapp database file inside the backup and copy it somewhere:

$ sqlite3 <backup>/Manifest.db "select fileID from Files where relativePath = 'ChatStorage.sqlite' and domain like '%whatsapp%';"
abcdef01234567890
$ cp <backup>/ab/abcdef01234567890 ~/Downloads/watoi/ChatStorage.sqlite

**Comment by Mc-muffin** [comment]
Well, you have your iPhone backup right? well just execute this command in terminal (replacing `<backup>` with the actual backup path)
`sqlite3 <backup>/Manifest.db "select fileID from Files where relativePath = 'ChatStorage.sqlite' and domain like '%whatsapp%';"`

The command above simplifies the chat database extraction, as Residentsummer said 

> For example, if the sqlite's output would have been d0ab3976ddce, your database file will be located at <backup>/d0/d0ab3976ddce. That is composed of the backup path + first two characters of the file name + the whole file name.

and is this `<backup>/d0/d0ab3976ddce` path the one you issue with this `cp /ab/abcdef01234567890 ~/Downloads/watoi/ChatStorage.sqlite` command

I might have made it easier to understand (I hope) but otherwise you can always ask a question.

**Comment by jorgallo** [comment]
Now i think i get it, but in terminal i get this error now, I think i am doing everything ok, or am i not? Anyway, I have used iExplorer to find ChatStorage.sqlite from that backup and now I have it in the desktop, can I do anything with that? 

![captura de pantalla 2018-01-23 a la s 16 58 47](https://user-images.githubusercontent.com/35620420/35305473-fb0ace2e-005e-11e8-9d12-458722576036.png)

**Comment by Mc-muffin** [comment]
If you already extracted the `ChatStorage.sqlite` file just run the importer as stated in the main page

- Extract the contents of Whatsapp.ipa (for the CoreData description files):

```
cd ~/Downloads/watoi
unzip ~/Downloads/WhatsApp_Messenger_x.y.z.ipa -d app
```

- Backup original database and run the migration:
```
cp ChatStorage.sqlite ~/Documents/SafePlace/
build/Release/watoi <path-to-msgstore.db> ChatStorage.sqlite app/Payload/WhatsApp.app/WhatsAppChat.momd
```
And then just replace the original database file on your backup (use iExplorer again if you must) and restore with iTunes.

**Comment by residentsummer** [comment]
cleanup
